apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../charts

helmCharts:
- name: training-operator
  includeCRDs: true
  valuesInline:
    rbac:
      create: true
    namespace: kubeflow
    image:
      repository: kubeflow/training-operator
      tag: latest
    webhook:
      create: true
      secret:
        create: true
  releaseName: training-operator
  version: 0.1.0 