apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: istio-cni-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: install-cni
        image: registry.k8s.io/busybox:1.28
