apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
data:
  config: |-
    templates:
      grpc-simple: |
        spec:
          initContainers:
            - name: grpc-bootstrap-init
              image: registry.k8s.io/busybox:1.28
