apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: seaweedfs
        args:
        - 'server'
        - '-dir=/data'
        - '-s3'
        - '-master.volumeSizeLimitMB=1024'  # Limit volume size to 1GB
